#include "Config_STM32.h"
#include "USBCore_STM32.h"
#include "HAL_STM32.h"
#include "debug.h"
#include "ffb_pro.h"
#ifdef USE_AS5600
#include "AS5600.h"
#endif

// --- HID Report Structure ---
typedef struct {
    int16_t x;
    int16_t y;
    int16_t z;
    int16_t rz;
    int16_t rx;
    uint32_t buttons;
} HID_InputReport_t;

// (Globals remain the same)
fwOpt fwOptions;
s16a accel, clutch, hbrake;
s32a brake;
s32v turn, axis, ffbs;
u32 button = 0;
// ... other globals

void TcaChannelSel(uint8_t addr, uint8_t ch) {
    uint8_t data = 1 << ch;
    hal_i2c_write(addr, &data, 1);
}

void setup() {
  // NOTE: main.c generated by CubeMX should call HAL_Init(), SystemClock_Config(),
  // and initialization for all peripherals (GPIO, ADC, TIM, I2C, USB_DEVICE).

  hal_init(); // Starts the microsecond timer

  // The original USBDevice.attach() is no longer needed as USB is handled by CubeMX init.

  ROTATION_MAX = int32_t(float(CPR) / 360.0 * float(ROTATION_DEG));
  ROTATION_MID = ROTATION_MAX >> 1;

  InitInputs();
  FfbSetDriver(0);
  InitPWM();

  last_refresh = hal_micros();
}

void loop() {
  now_micros = hal_micros();

  if ((now_micros - last_refresh) >= CONTROL_PERIOD) {
    last_refresh = now_micros;

    // --- Encoder Reading (Placeholder) ---
    // turn.x = read_encoder();

    axis.x = turn.x;
    ffbs = gFFB.CalcTorqueCommands(&axis);
    turn.x *= float(X_AXIS_PHYS_MAX) / float(ROTATION_MAX);
    turn.x = constrain(turn.x, -MID_REPORT_X - 1, MID_REPORT_X);

    SetPWM(&ffbs);

    // --- Analog Axis Reading ---
    // This assumes hal_pin_t structures are defined in Config_STM32.h for each pedal
    // accel.val = hal_adc_read(ACCEL_PIN_HAL);
    // brake.val = hal_adc_read(BRAKE_PIN_HAL);
    // clutch.val = hal_adc_read(CLUTCH_PIN_HAL);

    // (Calibration logic remains)

    button = readInputButtons();

    // (Shifter logic remains)

    // --- Send HID Report ---
    HID_InputReport_t report;
    report.x = turn.x + MID_REPORT_X + 1;
    report.y = brake.val;
    report.z = accel.val;
    report.rx = clutch.val;
    report.rz = hbrake.val;
    report.buttons = button;

    USB_SendInputReport(&report, sizeof(report));

    // (Config CDC logic needs porting)
  }
}
